version: '3.9'

services:
  mongodb:
    image: mongo:7
    ports:
      - 27018:27017
    networks:
      - app-network

  app:
    build:
      context: ./crud-rest-Node16
      dockerfile: Dockerfile
    ports:
      - 4444:4444
    depends_on:
      - mongodb
    networks:
      - app-network

  front:
    build:
      context: ./crud-rest-NG16
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - app-network

networks:
  app-network:
